version: '3'
services:
    api:
        build: .
        working_dir: /go/src/
        ports: 
            - '13240:1324'
        depends_on: 
            - db
        volumes: 
            - .:/go/src/
        command: sleep infinity
        restart: always
        container_name: taskbacklog_api
    db:
        image: mysql:latest
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        volumes:
            - "./initdb.d:/docker-entrypoint-initdb.d"
        ports:
            - '33100:3310'
        restart: always
        expose: 
            - '3310'
        environment:
            MYSQL_ROOT_PASSWORD: root
        container_name: taskbacklog_db